### ISSUE TITLE
'EMI experienced a critical exception while reloading, check log'

### ISSUE THREAD

**Issue by MechanosG** [emilyploszaj/emi#168]
Heya.  I'm in the early stages of playing around with building a 1.19.4 Quilt modpack.  Excited to give EMI a try and see how it compares to REI/JEI.  But I couldn't get it to work.  No crashing - just that message when I open my inventory, and none of EMI's GUI renders.  Peeking at the log, this seems to be the most relevant part -
```
[13:04:02] [Thread-21/ERROR]: [EMI] Critical error occured during reload:
[13:04:02] [Thread-21/INFO]: [STDERR]: java.lang.AbstractMethodError: Receiver class com.teamremastered.endrem.EndRemastered$$Lambda$5435/0x000000080186c3f8 does not define or inherit an implementation of the resolved method 'abstract void accept(net.minecraft.class_1761$class_8128, net.minecraft.class_1761$class_7704)' of interface net.minecraft.class_1761$class_7914.
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_47306(class_1761.java:96)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at net.minecraft.class_7706.method_47338(class_7706.java:2009)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at net.minecraft.class_7706.method_47337(class_7706.java:2009)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at net.minecraft.class_7706.method_47330(class_7706.java:2020)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at dev.emi.emi.EmiStackList.reload(EmiStackList.java:41)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:130)
[13:04:02] [Thread-21/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
So tried loading without End Remastered..  and..  EMI is now working, go figure.  I'll probably just leave End Remastered disabled for now so I can continue testing EMI (JEI worked fine with ER, but JEI more than halved my FPS even with the inventory closed! - REI partially works and my FPS stays high, but for some reason the right side block/item page stays empty - I wonder if End Remastered is breaking REI as well? o.o).  But I figure I should report the incompatibility anyway, in case you guys wanna try and resolve the conflict.

MC 1.19.4
Quilt 0.18.10
End Remastered 5.2.1
EMI 0.7.3
Extra Mod Interactions 0.3.0 (I tested with this both enabled and disabled, _just in case_)

**Comment by emilyploszaj** [comment]
If this is affecting REI it's likely an issue with End Remastered. They don't seem to have a 1.19.4 version, that may be part of the problem, but they'd know best what's going wrong.
