### ISSUE TITLE
Mekanism processing recipes support?

### ISSUE THREAD

**Issue by piotrb** [emilyploszaj/emi#196]
I loved the mod the moment I saw it on the list :)

But it does seem like it doesn't quite pick up all the different recipes JEI does .. so its not really usable on a heavily modded install :)

Not sure what else is missing, but Mekanism processing recipes are definitely not displaying .. and you can't even look up the recipe for something like an Infused Alloy nothing happens .. (while obviously with just JEI installed it does show its recipe)

**Comment by LemmaEOF** [comment]
Just to make sure, do you have both EMI and JEI installed at the same time? You need that in order for JEI recipes to be shown.

**Comment by emilyploszaj** [comment]
![image](https://github.com/emilyploszaj/emi/assets/14813658/efbfdf5b-71bb-4757-a819-7c8a95274140)
I was easily able to install Mekanism, JEI, and EMI and see the recipe. I believe Lemma is correct and you either forgot to install JEI, or you have something very wrong with your setup.

**Comment by piotrb** [comment]
I definitely have them all installed … I do have quite a large custom modpack going .. so maybe there is something subtly conflicting there .. I'll try to isolate it

**Comment by piotrb** [comment]
Ok I think I have the minimum repo mod list now .. 

* EMI

* Thermal Expansion
  * Thermal Foundation
    * Cofh Core

* Mekanism

* JEI
  * Just Enough Resources
  * Just Enough Advancements
    * LibX

Removing any of these mods makes the issue go away .. 
Well sort of .. Removing JER makes the issue persist on older worlds .. see notes below

---

Ok this is bizarrely inconsistent .. 
Launch -> Load World -> see the issue
Quit to title -> Load Same World -> don't see the issue


When reloading the world .. (and the recipe bug isn't there) .. 
The below error `[EMI] Exception loading plugin provided by jemi` .. disappears .. 
So likely that error is why the recipe isn't actually showing .. 

Also

Just Enough Resources has an odd impact on the worlds .. 
When you have the mod removed, creating a world doesn't manifest the issue .. 
Nor does re-loading that world after its been created .. 

Re-enabling JER .. then loading this same new world does manifest  the recipe issue

---

I'm seeing two errors .. 

```
11:14:23.230
jeresources
Render thread
Failed loading villager cartographer registered at cartographer
11:14:23.230
jeresources
Render thread
Exception caught when registering villager
java.lang.NullPointerException: Cannot read field "f_19853_" because "p_219708_" is null
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.npc.VillagerTrades$TreasureMapForEmeralds.m_213663_(VillagerTrades.java:877)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.collection.TradeList.addMerchantRecipe(TradeList.java:58)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.collection.TradeList.addITradeList(TradeList.java:69)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.entry.AbstractVillagerEntry.addITradeLists(AbstractVillagerEntry.java:30)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.entry.AbstractVillagerEntry.<init>(AbstractVillagerEntry.java:23)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.entry.VillagerEntry.<init>(VillagerEntry.java:19)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.util.VillagersHelper.initRegistry(VillagersHelper.java:23)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.compatibility.Compatibility.init(Compatibility.java:33)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14)
	at TRANSFORMER/jeresources@1.2.2.200/jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:88)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.load.PluginCaller.redirect$zza000$callOnPlugins(PluginCaller.java:531)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:88)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:117)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:114)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@11.6.0.1015/mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1321)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
11:14:23.289
mezz.jei.library.load.PluginCaller
Render thread
Registering categories: minecraft:jeresources took 184.8 ms
```

and

```
11:14:23.897
EMI
Thread-13
[EMI] [JEMI] Collecing data for World Gen
11:14:23.899
EMI
Thread-13
[EMI] Exception loading plugin provided by jemi
11:14:23.899
EMI
Thread-13
[EMI] java.lang.NullPointerException: Cannot invoke "mezz.jei.api.runtime.IJeiRuntime.getIngredientManager()" because "dev.emi.emi.jemi.JemiPlugin.runtime" is null
	at TRANSFORMER
11:14:23.899
EMI
Thread-13
[EMI] emi@1.0.1+1.19.2+forge
11:14:23.899
EMI
Thread-13
[EMI] dev.emi.emi.jemi.JemiPlugin.parseSubtypes(JemiPlugin.java:233)
	at TRANSFORMER
11:14:23.899
EMI
Thread-13
[EMI] emi@1.0.1+1.19.2+forge
11:14:23.899
EMI
Thread-13
[EMI] dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:203)
	at TRANSFORMER
11:14:23.899
EMI
Thread-13
[EMI] emi@1.0.1+1.19.2+forge
11:14:23.899
EMI
Thread-13
[EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:161)
	at java.base
11:14:23.899
EMI
Thread-13
[EMI] java.lang.Thread.run(Thread.java:833)
11:14:23.921
mezz.jei.library.load.PluginCaller
Render thread
Registering ingredients: jei:minecraft took 40.63 ms
```

**Comment by emilyploszaj** [comment]
I think this error is crashing JEI itself and not EMI? I really appreciate the effort to isolate this issue but it seems to be completely crashing JEI's reload, which would in turn mess up EMI's reload
