### ISSUE TITLE
[1.19.3 Fabric] Crash when right-clicking on Adorn Brewer

### ISSUE THREAD

**Issue by gamerpotion** [emilyploszaj/emi#209]
When using EMI with Adorn, and searching for "brewer" and rightclicking on it in EMI, then going to page 2 of 5, it results in the below crash.
you can replicate by installing
emi-1.0.2+1.19.3+fabric.jar
Adorn-4.1.1+1.19.3-fabric.jar

@Juuxel FYI.

```---- Minecraft Crash Report ----
// You're mean.

Time: 2023-06-11 11:57:48
Description: mouseClicked event handler

java.lang.IllegalArgumentException: All stacks of ingredient air x1 should be FluidVariants, but found air x1 with entry type class net.minecraft.class_1799
	at juuxel.adorn.compat.emi.FluidSlotWidget.<init>(FluidSlotWidget.kt:19)
	at juuxel.adorn.compat.emi.BrewingEmiRecipe.addWidgets(BrewingEmiRecipe.kt:66)
	at dev.emi.emi.screen.RecipeDisplay.getWidgets(RecipeDisplay.java:70)
	at dev.emi.emi.screen.RecipeTab.constructWidgets(RecipeTab.java:40)
	at dev.emi.emi.screen.RecipeScreen.setPage(RecipeScreen.java:378)
	at dev.emi.emi.screen.RecipeScreen.lambda$new$11(RecipeScreen.java:78)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at dev.emi.emi.screen.RecipeScreen.method_25402(RecipeScreen.java:444)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at juuxel.adorn.compat.emi.FluidSlotWidget.<init>(FluidSlotWidget.kt:19)
	at juuxel.adorn.compat.emi.BrewingEmiRecipe.addWidgets(BrewingEmiRecipe.kt:66)
	at dev.emi.emi.screen.RecipeDisplay.getWidgets(RecipeDisplay.java:70)
	at dev.emi.emi.screen.RecipeTab.constructWidgets(RecipeTab.java:40)
	at dev.emi.emi.screen.RecipeScreen.setPage(RecipeScreen.java:378)
	at dev.emi.emi.screen.RecipeScreen.lambda$new$11(RecipeScreen.java:78)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at dev.emi.emi.screen.RecipeScreen.method_25402(RecipeScreen.java:444)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)```

**Comment by Juuxel** [comment]
Your Adorn is outdated. This has been fixed in the latest release.

**Comment by gamerpotion** [comment]
> Your Adorn is outdated. This has been fixed in the latest release.

hey,  just wondering if thats been uploaded to CF?  cant download it via the client for 1.19.3

<img src="https://media.discordapp.net/attachments/964187610392199209/1117570186954944602/image.png?width=1101&height=671" />

**Comment by Juuxel** [comment]
I don't support 1.19.3 anymore - 1.19.2 and 1.19.4 are the current supported versions as the latest release (1.19.4 at the time of the previous Adorn release) and a special case (1.19.2).

**Comment by gamerpotion** [comment]
> I don't support 1.19.3 anymore - 1.19.2 and 1.19.4 are the current supported versions as the latest release (1.19.4 at the time of the previous Adorn release) and a special case (1.19.2).

Ok. Thats too bad.

**Comment by emilyploszaj** [comment]
This was actually also an EMI specific bug. 1.0.3 will prevent the crash, including in 1.19.3

**Comment by gamerpotion** [comment]
> This was actually also an EMI specific bug. 1.0.3 will prevent the crash, including in 1.19.3

Oh thanks!
am just testing it now,  it doesnt crash anymore but shows some render error.  Im guessing something needs to be on the Adorn side to fix that?

<img src="https://media.discordapp.net/attachments/964187610392199209/1118455995237138462/image.png?width=1702&height=671" />
