### ISSUE TITLE
[1.19.2] [Quilt] EMI errors out when opening inventory

### ISSUE THREAD

**Issue by KateReller** [emilyploszaj/emi#269]
EMI version: 1.0.17

Whole log file: https://mclo.gs/m8bagg1|

Error snippet

```
[00:07:42] [Thread-49/INFO]: [STDERR]: java.lang.UnsupportedOperationException: EntityEmiStack is not intended for NBT handling
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at io.github.pkstdev.emitrades.util.EntityEmiStack.getNbt(EntityEmiStack.java:82)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiStackList$StrictHashStrategy.hashCode(EmiStackList.java:245)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiStackList$StrictHashStrategy.hashCode(EmiStackList.java:228)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.add(ObjectOpenCustomHashSet.java:312)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiRecipes$Manager.lambda$new$8(EmiRecipes.java:176)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiRecipes$Manager.<init>(EmiRecipes.java:175)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiRecipes.bake(EmiRecipes.java:85)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:199)
[00:07:42] [Thread-49/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:07:42] [Thread-49/ERROR]: [EMI] Critical error occured during reload:
```

**Comment by emilyploszaj** [comment]
This is an EMI Trades issue, however, it should no longer be procced in 1.0.18
