### ISSUE TITLE
EmiIngredientSerializer console error

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#354]
https://mclo.gs/ybczi1W

Blank install (no other mods), latest version of EMI, 1.20.2 MC, Modrinth App.

```
{
  "type": "emi:world_interaction",
  "left": "item:minecraft:mud",
  "right": "item:minecraft:pointed_dripstone",
  "output": "item:minecraft:clay"
}
```

```
[01:18:33] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.24
[01:18:33] [main/INFO]: Loading 55 mods:
	- emi 1.0.24+1.20.2+fabric
	- fabric-api 0.90.7+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.75+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.5+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.11+bff13c85a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.8+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.6+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.10+e3d2bf3fa0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.41+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.10+bb1ee60ea0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.20.2
	- modmenu 8.0.0
[01:18:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:18:34] [main/INFO]: Compatibility level set to JAVA_17
[01:18:34] [main/WARN]: Error loading class: mezz/jei/library/load/PluginCaller (java.lang.ClassNotFoundException: mezz/jei/library/load/PluginCaller)
[01:18:50] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 590 milliseconds
[LWJGL] Version: 3.3.2-snapshot
	 OS: Windows 10 v10.0
	JRE: Windows amd64 17.0.8
	JVM: OpenJDK 64-Bit Server VM v17.0.8+7-LTS by Azul Systems, Inc.
[LWJGL] Loading JNI library: lwjgl
	Module: org.lwjgl
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\lwjgl.dll
[LWJGL] Loading library: jemalloc
	Module: org.lwjgl.jemalloc
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[01:18:56] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:18:56] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[LWJGL] Loading library: glfw
	Module: org.lwjgl.glfw
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\glfw.dll
[01:18:58] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[01:18:58] [Worker-Main-2/INFO]: Checking mod updates...
[01:18:59] [Worker-Main-2/INFO]: Update available for 'fabric-api@0.90.7+1.20.2', (-> 0.91.1+1.20.2)
[01:18:59] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[LWJGL] Loading JNI library: lwjgl_opengl
	Module: org.lwjgl.opengl
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
	Module: org.lwjgl.opengl
	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24
	Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
[LWJGL] Java 9 check intrinsics enabled
[LWJGL] Closure Registry: simple
[LWJGL] Java 10 multiplyHigh enabled
[LWJGL] Loading JNI library: lwjgl_stb
	Module: org.lwjgl.stb
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\lwjgl_stb.dll
[LWJGL] Java 9 text decoding enabled
[LWJGL] Loading library: OpenAL
	Module: org.lwjgl.openal
	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.2-0.14.24\OpenAL.dll
[01:19:02] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (emi, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu), file/Default
[01:19:03] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[01:19:05] [Worker-Main-2/ERROR]: [EMI] Exception deserializing stack "item:minecraft:mud"
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiIngredientSerializers.deserialize(EmiIngredientSerializers.java:74)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getDeserialized(EmiIngredientSerializer.java:23)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiData.lambda$init$30(EmiData.java:204)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiDataLoader.method_18789(EmiDataLoader.java:48)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18791(class_4080.java:11)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[01:19:05] [Worker-Main-2/ERROR]: [EMI] Exception deserializing stack "item:minecraft:pointed_dripstone"
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiIngredientSerializers.deserialize(EmiIngredientSerializers.java:74)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getDeserialized(EmiIngredientSerializer.java:23)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiData.lambda$init$30(EmiData.java:207)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiDataLoader.method_18789(EmiDataLoader.java:48)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18791(class_4080.java:11)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[01:19:05] [Worker-Main-2/ERROR]: [EMI] Exception deserializing stack "item:minecraft:clay"
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiIngredientSerializers.deserialize(EmiIngredientSerializers.java:74)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getDeserialized(EmiIngredientSerializer.java:23)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiData.lambda$init$30(EmiData.java:210)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at dev.emi.emi.data.EmiDataLoader.method_18789(EmiDataLoader.java:48)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18791(class_4080.java:11)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[01:19:05] [Worker-Main-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[01:19:08] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[01:19:08] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[01:19:08] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on �������� (Realtek High Definition Audio)
[01:19:08] [Render thread/INFO]: Sound engine started
[01:19:09] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[01:19:09] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[01:19:09] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[01:19:09] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/shield_patterns.png-atlas
[01:19:09] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[01:19:09] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[01:19:09] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[01:19:09] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[01:19:09] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[01:19:10] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[01:19:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[01:19:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[01:19:10] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[01:19:10] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[01:19:34] [Render thread/INFO]: Loaded 7 recipes
[01:19:35] [Render thread/INFO]: Loaded 1271 advancements
[01:19:35] [Render thread/INFO]: [EMI] Disconnecting from server, EMI data cleared
[01:19:35] [Thread-7/INFO]: [EMI] Clearing data
[01:19:35] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.687 ms
[01:19:35] [Server thread/INFO]: Starting integrated minecraft server version 1.20.2
[01:19:35] [Server thread/INFO]: Generating keypair
[01:19:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:42] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:43] [Render thread/INFO]: Preparing spawn area: 0%
[01:19:43] [Render thread/INFO]: Preparing spawn area: 12%
[01:19:44] [Render thread/INFO]: Preparing spawn area: 63%
[01:19:44] [Render thread/INFO]: Time elapsed: 7717 ms
[01:19:45] [Server thread/INFO]: Changing view distance to 12, from 10
[01:19:45] [Server thread/INFO]: Changing simulation distance to 12, from 0
[01:19:47] [Server thread/INFO]: {MINECRAFT_USERNAME}[local:E:08927571] logged in with entity id 18 at (8.491660762562269, -55.63180472284666, 0.06105416541242472)
[01:19:47] [Render thread/INFO]: [EMI] Recipes synchronized, waiting for tags to reload EMI...
[01:19:47] [Server thread/INFO]: {MINECRAFT_USERNAME} joined the game
[01:19:48] [Render thread/INFO]: [EMI] Joining server, EMI waiting for data from server...
[01:19:48] [Render thread/INFO]: [EMI] Tags synchronized, reloading EMI
[01:19:48] [Render thread/INFO]: [EMI] Starting Reload
[01:19:48] [Thread-11/INFO]: [EMI] Starting EMI reload...
[01:19:48] [Thread-11/INFO]: [EMI] Clearing data
[01:19:48] [Thread-11/INFO]: [EMI] Processing tags
[01:19:48] [Thread-11/INFO]: [EMI] Constructing index
[01:19:48] [Render thread/INFO]: Loaded 2 advancements
[01:19:49] [Thread-11/INFO]: [EMI] Loading plugin from emi
[01:19:49] [Thread-11/INFO]: [EMI] Reloaded plugin from emi in 777ms
[01:19:49] [Thread-11/INFO]: [EMI] Baking index
[01:19:50] [Thread-11/INFO]: [EMI] Registering late recipes
[01:19:50] [Thread-11/INFO]: [EMI] Baking recipes
[01:19:50] [Thread-11/INFO]: [EMI] Baked 2960 recipes in 478ms
[01:19:50] [Thread-11/INFO]: [EMI] Baking search
[01:19:50] [Thread-11/INFO]: [EMI] Finishing up
[01:19:50] [Thread-11/INFO]: [EMI] Reloaded EMI in 2660ms
[01:19:50] [Server thread/INFO]: Saving and pausing game...
[01:19:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[01:19:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[01:19:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
```

**Comment by emilyploszaj** [comment]
This should be actually really fixed in 1.0.25
