### ISSUE TITLE
[Bug] Crash when saving a favorite

### ISSUE THREAD

**Issue by Kiryonn** [emilyploszaj/emi#397]
| Minecraft | Modloader | Mod |
|---|---|---|
| 1.20.1 | Fabric 0.15.3 | 1.0.29 |

Here are the logs from the moment i clicked the favorite key on a random item within the index:
<details>
<summary>LOG</summary>

```
[03/01/2024 17:17:28 PM] [Render thread/INFO] [EMI] Discovered Sodium
[03/01/2024 17:17:29 PM] [Server thread/INFO] Saving and pausing game...
[03/01/2024 17:17:29 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:overworld
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:prison
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:insufferable_crypt
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:the_end
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:promenade
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:ramparts
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:black_bridge
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/dungeonz:dungeon
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/deeperdarker:otherside
[03/01/2024 17:17:31 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:the_nether
[03/01/2024 17:17:38 PM] [Server thread/WARN] Can't keep up! Is the server overloaded? Running 2060ms or 41 ticks behind
[03/01/2024 17:17:40 PM] [Server thread/INFO] Stopping server
[03/01/2024 17:17:40 PM] [Server thread/INFO] Saving players
[03/01/2024 17:17:40 PM] [Server thread/INFO] Saving worlds
[03/01/2024 17:17:42 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:overworld
[03/01/2024 17:17:51 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:prison
[03/01/2024 17:17:51 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:insufferable_crypt
[03/01/2024 17:17:51 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:the_end
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:promenade
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:ramparts
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecells:black_bridge
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/dungeonz:dungeon
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/deeperdarker:otherside
[03/01/2024 17:17:52 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[Survive]'/minecraft:the_nether
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (Survive): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (prison): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (insufferable_crypt): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (promenade): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (ramparts): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (black_bridge): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (otherside): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[03/01/2024 17:17:52 PM] [Server thread/INFO] ThreadedAnvilChunkStorage: All dimensions are saved
[03/01/2024 17:17:57 PM] [Server thread/INFO] closing rrp ebe:base_resources
[03/01/2024 17:17:57 PM] [Render thread/INFO] [EMI] Disconnecting from server, EMI data cleared
[03/01/2024 17:17:57 PM] [Thread-28/INFO] [EMI] Clearing data
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.lambda$testAvailable$2(ConfigDataHolderImpl.java:88)
[03/01/2024 17:17:57 PM] 	at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.testAvailable(ConfigDataHolderImpl.java:87)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.getOrCreateDefaultConfig(ConfigDataHolderImpl.java:54)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.getConfig(ConfigDataHolderImpl.java:49)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.api.config.v3.ConfigHolder.get(ConfigHolder.java:42)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.config.ConfigHolderRegistry.get(ConfigHolderRegistry.java:16)
[03/01/2024 17:17:57 PM] 	at fuzs.illagerinvasion.handler.PlatinumTrimHandler.getPlatinumTrim(PlatinumTrimHandler.java:64)
[03/01/2024 17:17:57 PM] 	at fuzs.illagerinvasion.client.handler.EnchantmentTooltipHandler.onItemTooltip$2(EnchantmentTooltipHandler.java:49)
[03/01/2024 17:17:57 PM] 	at fuzs.puzzleslib.impl.client.event.FabricClientEventInvokers.lambda$register$7(FabricClientEventInvokers.java:98)
[03/01/2024 17:17:57 PM] 	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:34)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1799.handler$dig001$fabric-item-api-v1$getTooltip(class_1799.java:8611)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1799.method_7950(class_1799.java:791)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_1485(class_310.java:839)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_7454.method_43796(class_7454.java:20)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1126.method_4799(class_1126.java:26)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:61)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1124.method_43804(class_1124.java:42)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_43759(class_310.java:2653)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_46740(class_310.java:857)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1761.method_47314(class_1761.java:128)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1761.method_47306(class_1761.java:107)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_7706.method_47331(class_7706.java:2054)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03/01/2024 17:17:57 PM] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_7706.method_47337(class_7706.java:2054)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_7706.callUpdateEntries$polymer-core_$md$3ab0ef$0(class_7706.java)
[03/01/2024 17:17:57 PM] 	at eu.pb4.polymer.core.mixin.other.ItemGroupsAccessor.callUpdateEntries(ItemGroupsAccessor.java)
[03/01/2024 17:17:57 PM] 	at eu.pb4.polymer.core.impl.client.InternalClientRegistry.lambda$clear$6(InternalClientRegistry.java:339)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_1255.execute(class_1255.java:102)
[03/01/2024 17:17:57 PM] 	at eu.pb4.polymer.core.impl.client.InternalClientRegistry.clear(InternalClientRegistry.java:325)
[03/01/2024 17:17:57 PM] 	at eu.pb4.polymer.core.impl.client.InternalClientRegistry.disable(InternalClientRegistry.java:170)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.handler$hoi000$polymer-core$polymer$onDisconnect(class_310.java:29050)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_18096(class_310.java:2197)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_1519(class_310.java:1392)
[03/01/2024 17:17:57 PM] 	at net.minecraft.class_310.method_1514(class_310.java:822)
[03/01/2024 17:17:57 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[03/01/2024 17:17:57 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[03/01/2024 17:17:57 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2024 17:17:57 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2024 17:17:57 PM] [Render thread/ERROR] Calling server config when it is not yet available! This is a bug! Message: Config data is missing
[03/01/2024 17:17:59 PM] [Render thread/INFO] Stopping worker threads
[03/01/2024 17:17:59 PM] [Render thread/INFO] emissive suffixes loaded: {_e}.
[03/01/2024 17:17:59 PM] [Render thread/INFO] Clearing 'BetterStatsClientNetworkHandler' flags.
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_437.method_25412(class_437.java:414)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1466(class_309.java:391)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22678(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1255.execute(class_1255.java:102)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22676(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1041.method_15998(class_1041.java:288)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1241)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1514(class_310.java:802)
[03/01/2024 17:18:00 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2024 17:18:00 PM] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_342.method_20315()" because "searchBox" is null
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.handler$bhg000$brb$onKeyPressed(class_465.java:2211)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.method_25404(class_465.java)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1454(class_309.java:395)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_437.method_25412(class_437.java:409)
[03/01/2024 17:18:00 PM] 	... 16 more
[03/01/2024 17:18:00 PM] [Render thread/FATAL] Reported exception thrown!
[03/01/2024 17:18:00 PM] ---- Minecraft Crash Report ----
[03/01/2024 17:18:00 PM] // Don't be sad, have a hug! <3
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] Time: 2024-01-03 17:18:00
[03/01/2024 17:18:00 PM] Description: keyPressed event handler
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] java.lang.NullPointerException: Cannot invoke "net.minecraft.class_342.method_20315()" because "searchBox" is null
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.handler$bhg000$brb$onKeyPressed(class_465.java:2211)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.method_25404(class_465.java)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1454(class_309.java:395)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_437.method_25412(class_437.java:409)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1466(class_309.java:391)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22678(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1255.execute(class_1255.java:102)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22676(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1041.method_15998(class_1041.java:288)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1241)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1514(class_310.java:802)
[03/01/2024 17:18:00 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[03/01/2024 17:18:00 PM] ---------------------------------------------------------------------------------------
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] -- Head --
[03/01/2024 17:18:00 PM] Thread: Render thread
[03/01/2024 17:18:00 PM] Stacktrace:
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.handler$bhg000$brb$onKeyPressed(class_465.java:2211)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_465.method_25404(class_465.java)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1454(class_309.java:395)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_437.method_25412(class_437.java:409)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1466(class_309.java:391)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22678(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1255.execute(class_1255.java:102)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22676(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] -- Affected screen --
[03/01/2024 17:18:00 PM] Details:
[03/01/2024 17:18:00 PM] 	Screen name: net.minecraft.class_490
[03/01/2024 17:18:00 PM] Stacktrace:
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_437.method_25412(class_437.java:409)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_1466(class_309.java:391)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22678(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1255.execute(class_1255.java:102)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_309.method_22676(class_309.java:477)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/01/2024 17:18:00 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[03/01/2024 17:18:00 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_1041.method_15998(class_1041.java:288)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1241)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1514(class_310.java:802)
[03/01/2024 17:18:00 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] -- Affected level --
[03/01/2024 17:18:00 PM] Details:
[03/01/2024 17:18:00 PM] 	All players: 1 total; [class_746['**MINECRAFTUSERNAME**'/132, l='ClientLevel', x=386.30, y=65.00, z=782.70]]
[03/01/2024 17:18:00 PM] 	Chunk stats: 1024, 609
[03/01/2024 17:18:00 PM] 	Level dimension: minecraft:overworld
[03/01/2024 17:18:00 PM] 	Level spawn location: World: (0,76,5), Section: (at 0,12,5 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[03/01/2024 17:18:00 PM] 	Level time: 56501 game time, 101805 day time
[03/01/2024 17:18:00 PM] 	Server brand: fabric
[03/01/2024 17:18:00 PM] 	Server type: Integrated singleplayer server
[03/01/2024 17:18:00 PM] Stacktrace:
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_638.method_8538(class_638.java:458)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1587(class_310.java:2406)
[03/01/2024 17:18:00 PM] 	at net.minecraft.class_310.method_1514(class_310.java:821)
[03/01/2024 17:18:00 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03/01/2024 17:18:00 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] -- Last reload --
[03/01/2024 17:18:00 PM] Details:
[03/01/2024 17:18:00 PM] 	Reload number: 1
[03/01/2024 17:18:00 PM] 	Reload reason: initial
[03/01/2024 17:18:00 PM] 	Finished: Yes
[03/01/2024 17:18:00 PM] 	Packs: vanilla, fabric, presencefootsteps:default_sound_pack, minecraft:supporteatinganimation
[03/01/2024 17:18:00 PM] 
[03/01/2024 17:18:00 PM] -- System Details --
[03/01/2024 17:18:00 PM] Details:
[03/01/2024 17:18:00 PM] 	Minecraft Version: 1.20.1
[03/01/2024 17:18:00 PM] 	Minecraft Version ID: 1.20.1
[03/01/2024 17:18:00 PM] 	Operating System: Windows 10 (amd64) version 10.0
[03/01/2024 17:18:00 PM] 	Java Version: 17.0.3, Microsoft
[03/01/2024 17:18:00 PM] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[03/01/2024 17:18:00 PM] 	Memory: 2940760880 bytes (2804 MiB) / 6509559808 bytes (6208 MiB) up to 12884901888 bytes (12288 MiB)
[03/01/2024 17:18:00 PM] 	CPUs: 8
[03/01/2024 17:18:00 PM] 	Processor Vendor: AuthenticAMD
[03/01/2024 17:18:00 PM] 	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
[03/01/2024 17:18:00 PM] 	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
[03/01/2024 17:18:00 PM] 	Microarchitecture: Zen / Zen+
[03/01/2024 17:18:00 PM] 	Frequency (GHz): 2.10
[03/01/2024 17:18:00 PM] 	Number of physical packages: 1
[03/01/2024 17:18:00 PM] 	Number of physical CPUs: 4
[03/01/2024 17:18:00 PM] 	Number of logical CPUs: 8
[03/01/2024 17:18:00 PM] 	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
[03/01/2024 17:18:00 PM] 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
[03/01/2024 17:18:00 PM] 	Graphics card #0 VRAM (MB): 2048.00
[03/01/2024 17:18:00 PM] 	Graphics card #0 deviceId: 0x15d8
[03/01/2024 17:18:00 PM] 	Graphics card #0 versionInfo: DriverVersion=27.20.21034.37
[03/01/2024 17:18:00 PM] 	Memory slot #0 capacity (MB): 8192.00
[03/01/2024 17:18:00 PM] 	Memory slot #0 clockSpeed (GHz): 2.40
[03/01/2024 17:18:00 PM] 	Memory slot #0 type: DDR4
[03/01/2024 17:18:00 PM] 	Memory slot #1 capacity (MB): 16384.00
[03/01/2024 17:18:00 PM] 	Memory slot #1 clockSpeed (GHz): 2.40
[03/01/2024 17:18:00 PM] 	Memory slot #1 type: DDR4
[03/01/2024 17:18:00 PM] 	Virtual memory max (MB): 25802.14
[03/01/2024 17:18:00 PM] 	Virtual memory used (MB): 22089.15
[03/01/2024 17:18:00 PM] 	Swap memory total (MB): 3328.00
[03/01/2024 17:18:00 PM] 	Swap memory used (MB): 289.48
[03/01/2024 17:18:00 PM] 	JVM Flags: 10 total; -Xmx12288M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
[03/01/2024 17:18:00 PM] 		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
[03/01/2024 17:18:00 PM] 			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
[03/01/2024 17:18:00 PM] 				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
[03/01/2024 17:18:00 PM] 			polymer-core: Polymer (Core) 0.5.15+1.20.1
[03/01/2024 17:18:01 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[03/01/2024 17:18:01 PM] Checking for updated files!
```
</details>

**Comment by emilyploszaj** [comment]
This seems to be a crash from a mod with the mixin initials "brb", EMI is not present in the stack traces here.

**Comment by Kiryonn** [comment]
> This seems to be a crash from a mod with the mixin initials "brb", EMI is not present in the stack traces here.

Ho right, I have the same keybind for "better recipe book" and EMI to favorite items. Thanks for pointing that out.
