### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by YannYB** [emilyploszaj/emi#44]
Hi, when I open my inventory I crash instantly. The strange thing is that when I open a chest or other thing with gui that is not the inventory, the screen become blur (because of my mod blur) and there is no screen

Its horrible please help me.

Thanks.

**Comment by emilyploszaj** [comment]
I need a crashlog or a mod list to help.

**Comment by fzzyhmstrs** [comment]
I may be seeing a similar/same issue. When I try to open a container screen, I get the below error thrown. I am not crashing when I try to open my inventory, but my containers are simply not opening at all. the `use` action on them does nothing but the error.

Mods installed (first and last are my own, and the issue happens with my modded containers but not vanilla):
![image](https://user-images.githubusercontent.com/72876796/180888932-da5d09cc-79a4-49ff-a4a0-43fb6c3ec67d.png)

When I remove EMI, the screens work per usual.

```
[17:25:38] [Render thread/ERROR] (Minecraft) Error executing task on Client
 java.lang.NullPointerException: Cannot read field "keyboard" because "this.client" is null
	at net.minecraft.client.gui.screen.ingame.HandledScreen.handler$zoe003$init(HandledScreen.java:2232) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.init(HandledScreen.java:93) ~[minecraft-project-@-merged-named.jar:?]
	at me.fzzyhmstrs.amethyst_imbuement.screen.AltarOfExperienceScreen.<init>(AltarOfExperienceScreen.kt:175) ~[main/:?]
	at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterScreen.registerAll$lambda-1(RegisterScreen.kt:23) ~[main/:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreens$Provider.open(HandledScreens.java:62) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreens.open(HandledScreens.java:51) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onOpenScreen(ClientPlayNetworkHandler.java:1053) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.s2c.play.OpenScreenS2CPacket.apply(OpenScreenS2CPacket.java:37) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.s2c.play.OpenScreenS2CPacket.apply(OpenScreenS2CPacket.java:11) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1095) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:734) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by fzzyhmstrs** [comment]
I'm not seeing the issue with 0.2.0+1.19 by the way:
![image](https://user-images.githubusercontent.com/72876796/180889980-87a28c78-3f79-4ba1-a8c9-86153f86c2da.png)

**Comment by fzzyhmstrs** [comment]
I figured out the issue for my particular problem, which was on my end, so I've hidden the above two comments. The original comment may still need pursuing if they provide details.

**Comment by YannYB** [comment]
Closing it, that was one of my mods that was causing issues
