### ISSUE TITLE
[Forge - 1.19.2]: Game froze when searching too early in creative menu

### ISSUE THREAD

**Issue by SiverDX** [emilyploszaj/emi#461]
Version: 1.1.2

Way too many mods to list
The search itself works fine normally, first time running into this (then again i pretty much never use the creative search)

```
[10Mar2024 01:44:01.166] [Thread-40/INFO] [EMI/]: [EMI] Baked 86901 recipes in 2820ms
[10Mar2024 01:44:01.205] [Thread-40/INFO] [EMI/]: [EMI] Baking search
[10Mar2024 01:44:03.082] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 2101ms or 42 ticks behind
[10Mar2024 01:44:03.565] [Thread-43/INFO] [EMI/]: [EMI] Baked recipes after reload in 2429ms
[10Mar2024 01:44:05.932] [Thread-40/INFO] [EMI/]: [EMI] Finishing up
[10Mar2024 01:44:05.954] [Thread-40/INFO] [EMI/]: [EMI] Reloaded EMI in 22911ms
[10Mar2024 01:44:05.962] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Index 4 out of bounds for length 4
	Index: 5
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplClient eventContainerScreenEvent(Lnet/minecraftforge/client/event/ContainerScreenEvent$Render$Foreground;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1769/0x000000080141e000@19871454
		4: ASM: org.anti_ad.mc.ipnext.forge.ForgeEventHandler@461c4cb9 onForegroundRender(Lnet/minecraftforge/client/event/ContainerScreenEvent$Render$Foreground;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1769/0x000000080141e000@2015c6ce
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.remove(Unknown Source)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.screen.StackBatcher$ClaimedCollection.claim(StackBatcher.java:238)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.screen.EmiScreenManager$ScreenSpace.<init>(EmiScreenManager.java:1568)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.screen.EmiScreenManager.createScreenSpace(EmiScreenManager.java:343)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.screen.EmiScreenManager.recalculate(EmiScreenManager.java:182)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.screen.EmiScreenManager.render(EmiScreenManager.java:587)
	at TRANSFORMER/emi@1.1.2+1.19.2+forge/dev.emi.emi.platform.forge.EmiClientForge.renderScreenForeground(EmiClientForge.java:83)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:120)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6305_(EffectRenderingInventoryScreen.java:28)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:605)
	at TRANSFORMER/forge@43.3.0/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441)
	at TRANSFORMER/forge@43.3.0/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

**Comment by emilyploszaj** [comment]
This actually seems like a really peculiar conmodex related to EMI's batched renderer, unrelated to creative searching, I'll look into it but I haven't been able to reproduce this yet.
