### ISSUE TITLE
Crash on creating new world

### ISSUE THREAD

**Issue by emeryplyler** [emilyploszaj/emi#489]
I was running a modpack where I had disabled some of the mods and added in EMI and MouseWheelie. Not expecting it to work, I tried to load an old singleplayer world from before I had removed a bunch of mods and got a nullpointer exception and then the game put me at the server selection. I then tried to create a new world and it got stuck. I scrolled up from the point in the log where I killed the process up to a place where it seems to be placing the strongholds in the new world. I used MultiMC.

If you need it, I will post the modlist from before and after I removed some. It's modified from Realistic Survival 1.2.

PS: I love your mod. Thank you for your time and your hard work :)

```
[20:15:59] [Server thread/INFO]: [STDOUT]: Initializing stronghold positions, this may take a while
[20:15:59] [Server thread/INFO]: [STDOUT]: Stronghold positions initialized
[20:15:59] [Server thread/INFO]: [STDOUT]: Initializing stronghold positions, this may take a while
[20:15:59] [Server thread/INFO]: [STDOUT]: Stronghold positions initialized
[20:15:59] [Server thread/INFO]: [STDOUT]: Initializing stronghold positions, this may take a while
[20:15:59] [Server thread/INFO]: [STDOUT]: Stronghold positions initialized
[20:15:59] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:16:00] [C2ME worker #5/WARN]: Empty or non-existent pool: minecraft:
[20:16:00] [C2ME worker #5/WARN]: Empty or non-existent pool: minecraft:
[20:16:00] [C2ME worker #5/WARN]: Empty or non-existent pool: minecraft:
[20:16:00] [C2ME worker #5/WARN]: Empty or non-existent pool: minecraft:
[20:16:00] [Render thread/INFO]: Time elapsed: 403000 ms
[20:16:00] [Server thread/INFO]: Encoded Weapon Attribute registry size (with package overhead): 27798 bytes (in 3 string chunks with the size of 10000)
[20:16:00] [Server thread/INFO]: [More Mobs] Sending global config to server...
[20:16:00] [Server thread/INFO]: Created new objective [ts.mm.settings]
[20:16:00] [Server thread/INFO]: [STDOUT]: Encoded SpellRegistry size (with package overhead): 16656 bytes (in 2 string chunks with the size of 10000)
[20:16:00] [Server thread/INFO]: Reload Config
[20:16:00] [Server thread/INFO]: Reloaded configs for wandering_collector (universal/world)
[20:16:00] [Server thread/INFO]: Reloaded configs for mousewheelie (universal/world)
[20:16:01] [C2ME worker #8/WARN]: Empty or non-existent pool: minecraft:
[20:16:01] [C2ME worker #8/WARN]: Empty or non-existent pool: minecraft:
[20:16:01] [C2ME worker #8/WARN]: Empty or non-existent pool: minecraft:
[20:16:01] [C2ME worker #8/WARN]: Empty or non-existent pool: minecraft:
[20:16:10] [Server thread/INFO]: [Handshake] Sending channel query
[20:16:10] [Netty Local Client IO #2/INFO]: [Handshake] Sending client channels
[20:16:10] [Server thread/INFO]: Changing view distance to 8, from 10
[20:16:10] [Netty Server IO #5/INFO]: [Handshake] Receiving client channels
[20:16:10] [Netty Server IO #5/INFO]: [Handshake] Handshake completed successfully
[20:16:10] [Server thread/INFO]: Changing simulation distance to 6, from 0
[20:16:10] [Server thread/INFO]: [Starter Structure] Generating starter structure with 520 blocks.
[20:16:10] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 9596ms or 191 ticks behind
[20:16:10] [Netty Local Client IO #2/INFO]: Connected to a modded server.
[20:16:10] [Netty Local Client IO #2/INFO]: Canceling Microsoft telemetry
[20:16:14] [Server thread/INFO]: Shinji__Kun[local:E:cb9ff1a3] logged in with entity id 1460 at (-1.5, 78.0, 6.5)
[20:16:14] [Server thread/WARN]: [bclib] Server changed!
[20:16:14] [Server thread/INFO]: Sending server config values to client
[20:16:14] [Netty Local Client IO #2/INFO]: Applying server overrides
[20:16:14] [Netty Local Client IO #2/INFO]: Responding with client values
[20:16:14] [Netty Server IO #5/INFO]: Receiving client config
[20:16:14] [Server thread/INFO]: Syncing config to Shinji__Kun (71450d9e-1776-44fe-8b67-6805160c72bb)
[20:16:14] [Netty Local Client IO #2/INFO]: Decoded Weapon Attribute registry in 3 string chunks
[20:16:14] [Server thread/INFO]: {PlayerPersisted:{}}
[20:16:14] [Server thread/INFO]: Shinji__Kun joined the game
[20:16:14] [Render thread/INFO]: New minimap session initialized!
[20:16:14] [Render thread/INFO]: New world map session initialized!
[20:16:14] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='overworld'}
[20:16:14] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[20:16:14] [Server thread/INFO]: [Nbt Crafting] Syncing advanced recipe data to player Shinji__Kun
[20:16:14] [Render thread/INFO]: Starting custom uniform resolving
[20:16:15] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:252) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:663) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35) ~[iris-mc1.19.2-1.6.9.jar:?]
	at net.minecraft.class_310.handler$eop000$iris$resetPipeline(class_310.java:25498) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2097) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:386) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$cdg000$c2me-opts-scheduling$redirectExecuteTask(class_1255.java:521) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:16:16] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[20:16:17] [Render thread/INFO]: Started 8 worker threads
[20:16:17] [Render thread/INFO]: [bclib] Sending hello to server.
[20:16:17] [Render thread/INFO]: [EMI] Joining server, EMI waiting for data from server...
[20:16:17] [Render thread/INFO]: Received config from the server: 
[20:16:17] [Render thread/WARN]: Failed to get file path of mod moonlight
[20:16:17] [Render thread/WARN]: Failed to get file path of mod supplementaries
[20:16:17] [Render thread/WARN]: Failed to get file path of mod everycomp
[20:16:17] [Render thread/WARN]: Failed to get file path of mod labels
[20:16:17] [Render thread/INFO]: Synced supplementaries-common.json configs
[20:16:17] [Render thread/INFO]: [Fabric Seasons] Received dedicated server crops.
[20:16:17] [Render thread/INFO]: Synced Flute Songs
[20:16:17] [Render thread/INFO]: Synced Captured Mobs settings
[20:16:17] [Render thread/INFO]: Synced Globe data
[20:16:17] [Render thread/INFO]: Synced Hourglass data
[20:16:17] [Render thread/INFO]: [EMI] Tags synchronized, waiting for recipes to reload EMI...
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:arcane_rune_medium_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:frost_rune_medium_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:fire_rune_small_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:healing_rune_medium_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:arcane_rune_small_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:fire_rune_medium_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:frost_rune_small_altar
[20:16:17] [Render thread/WARN]: Unknown recipe category: runes:crafting/runes:healing_rune_small_altar
[20:16:17] [Render thread/INFO]: [EMI] Recipes synchronized, reloading EMI
[20:16:17] [Render thread/INFO]: [EMI] Starting Reload
[20:16:17] [Thread-65/INFO]: [EMI] Starting EMI reload...
[20:16:17] [Thread-65/INFO]: [EMI] Clearing data
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from emi
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from emi in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from bclib
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from bclib in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from betternether
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from betternether in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from environmentz
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from environmentz in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from levelz
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from levelz in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from polymer
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from polymer in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from runic_enchanting
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from runic_enchanting in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from supplementaries
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from supplementaries in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from trinkets-curios-theme
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from trinkets-curios-theme in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Initializing plugin from villagerquests
[20:16:17] [Thread-65/INFO]: [EMI] Initialized plugin from villagerquests in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Processing tags
[20:16:17] [Thread-65/INFO]: [EMI] Constructing index
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from emi
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from emi in 140ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from bclib
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from bclib in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from betternether
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from betternether in 1ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from environmentz
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from environmentz in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from levelz
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from levelz in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from polymer
[20:16:17] [Thread-65/ERROR]: [EMI] Exception loading plugin provided by polymer
[20:16:17] [Thread-65/INFO]: [STDERR]: java.lang.NoClassDefFoundError: dev/emi/emi/EmiStackList
[20:16:17] [Thread-65/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.client.compat.EmiCompatibility.update(EmiCompatibility.java:56)
[20:16:17] [Thread-65/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.client.compat.EmiCompatibility.register(EmiCompatibility.java:46)
[20:16:17] [Thread-65/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
[20:16:17] [Thread-65/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[20:16:17] [Thread-65/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: dev.emi.emi.EmiStackList
[20:16:17] [Thread-65/INFO]: [STDERR]: 	... 4 more
[20:16:17] [Thread-65/ERROR]: [EMI] java.lang.NoClassDefFoundError: dev
[20:16:17] [Thread-65/ERROR]: [EMI] emi
[20:16:17] [Thread-65/ERROR]: [EMI] emi
[20:16:17] [Thread-65/ERROR]: [EMI] EmiStackList
	at eu.pb4.polymer.impl.client.compat.EmiCompatibility.update(EmiCompatibility.java:56)
	at eu.pb4.polymer.impl.client.compat.EmiCompatibility.register(EmiCompatibility.java:46)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
	at java.base
[20:16:17] [Thread-65/ERROR]: [EMI] java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: dev.emi.emi.EmiStackList
	... 4 more

[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from runic_enchanting
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from runic_enchanting in 1ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from supplementaries
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from supplementaries in 4ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from trinkets-curios-theme
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from trinkets-curios-theme in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Loading plugin from villagerquests
[20:16:17] [Thread-65/INFO]: [EMI] Reloaded plugin from villagerquests in 0ms
[20:16:17] [Thread-65/INFO]: [EMI] Baking index
[20:16:17] [Thread-65/INFO]: [EMI] Registering late recipes
[20:16:17] [Thread-65/INFO]: [EMI] Baking recipes
[20:16:17] [Thread-65/ERROR]: [EMI] Untranslated recipe category runic_enchanting:emi.rune_enchanting_category
[20:16:17] [Thread-65/ERROR]: [EMI] Untranslated recipe category runic_enchanting:emi.rune_scribing_category
[20:16:17] [Thread-65/INFO]: [EMI] Baked 8884 recipes in 143ms
[20:16:17] [Thread-65/INFO]: [EMI] Baking search
[20:16:17] [Render thread/INFO]: Minimap updated server level id: -2124079805 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[20:16:18] [Render thread/INFO]: [STDOUT]: io.github.apace100.origins.screen.ChooseOriginScreen
[20:16:18] [Thread-66/ERROR]: [EMI] Untranslated recipe category runic_enchanting:emi.rune_enchanting_category
[20:16:18] [Thread-66/ERROR]: [EMI] Untranslated recipe category runic_enchanting:emi.rune_scribing_category
[20:16:18] [Render thread/INFO]: Loaded 34 advancements
[20:16:18] [Thread-66/INFO]: [EMI] Baked recipes after reload in 111ms
[20:16:18] [Thread-65/INFO]: [EMI] Finishing up
[20:16:18] [Thread-65/INFO]: [EMI] Reloaded EMI in 550ms
[20:16:18] [Worker-Main-9/ERROR]: Error while loading the animated skin.
java.io.IOException: Server returned HTTP response code: 521 for URL: https://skins.trsha.re/71450d9e-1776-44fe-8b67-6805160c72bb.gif
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:?]
	at dev.tr7zw.notenoughanimations.donor.DonorSkinProvider$1.run(DonorSkinProvider.java:100) [notenoughanimations-fabric-1.6.2-mc1.19.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
[20:16:23] [Server thread/INFO]: [bclib] Received Hello from Client. (server=2.1.7, client=2.1.7)
[20:16:23] [Server thread/INFO]: [bclib] Auto-Sync is disabled for Singleplayer worlds.
[20:16:23] [Netty Local Client IO #2/ERROR]: Exception occurred in netty pipeline
java.lang.NoClassDefFoundError: dev/emi/emi/EmiReloadManager
	at eu.pb4.polymer.impl.client.compat.EmiCompatibility.lambda$static$1(EmiCompatibility.java:32) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.api.utils.events.SimpleEvent.invoke(SimpleEvent.java:26) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.impl.client.InternalClientRegistry.clear(InternalClientRegistry.java:320) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.impl.client.networking.PolymerClientProtocolHandler.run(PolymerClientProtocolHandler.java:228) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.impl.client.networking.PolymerClientProtocolHandler.handle(PolymerClientProtocolHandler.java:142) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.impl.client.networking.PolymerClientProtocolHandler.handle(PolymerClientProtocolHandler.java:77) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at net.minecraft.class_634.handler$hoa000$polymer$catchPackets(class_634.java:13505) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.emi.emi.EmiReloadManager
	... 69 more
[20:16:23] [Server thread/INFO]: Saving and pausing game...
[20:16:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:16:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:16:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dungeonz:dungeon
[20:16:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:19:22] [Render thread/INFO]: [STDOUT]: io.github.apace100.origins.screen.WaitForNextLayerScreen
Process was killed by user.
```

**Comment by emilyploszaj** [comment]
This is a crash from the mod Polymer. You should update it.

**Comment by emeryplyler** [comment]
I can't find it in the mods folder and none of the mods that embed it are in the mods folder either. Should I install it?

**Comment by emilyploszaj** [comment]
It's in your log so one of your mods has it installed. Installing a newer version manually will update it

**Comment by emeryplyler** [comment]
It was Universal Graves that installed it. Thank you!
