### ISSUE TITLE
BCLib

### ISSUE THREAD

**Issue by lanwoodall423** [emilyploszaj/emi#648]
1.20.1 Fabric with EMI 1.1.10 and BCLib 3.0.14

Endless loop of EMI trying to initialize and failing at:

[11:12:01] [Thread-36/ERROR]: [worlds_together] Tried to read from global registry!
[11:12:01] [Thread-36/ERROR]: [EMI] Exception loading plugin provided by bclib
[11:12:01] [Thread-36/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because the return value of "org.betterx.worlds.together.world.event.WorldBootstrap.getLastRegistryAccessOrElseBuiltin()" is null
[11:12:01] [Thread-36/INFO]: [STDERR]: 	at org.betterx.bclib.recipes.AnvilRecipe.getAllHammers(AnvilRecipe.java:108)
[11:12:01] [Thread-36/INFO]: [STDERR]: 	at org.betterx.bclib.integration.emi.EMIAnvilRecipe.addAllRecipes(EMIAnvilRecipe.java:45)
[11:12:01] [Thread-36/INFO]: [STDERR]: 	at org.betterx.bclib.integration.emi.EMIPlugin.register(EMIPlugin.java:120)
[11:12:01] [Thread-36/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
[11:12:01] [Thread-36/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:12:01] [Thread-36/ERROR]: [EMI] java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because the return value of "org.betterx.worlds.together.world.event.WorldBootstrap.getLastRegistryAccessOrElseBuiltin()" is null
	at org.betterx.bclib.recipes.AnvilRecipe.getAllHammers(AnvilRecipe.java:108)
	at org.betterx.bclib.integration.emi.EMIAnvilRecipe.addAllRecipes(EMIAnvilRecipe.java:45)
	at org.betterx.bclib.integration.emi.EMIPlugin.register(EMIPlugin.java:120)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base
[11:12:01] [Thread-36/ERROR]: [EMI] java.lang.Thread.run(Thread.java:1583)

[latest.log](https://github.com/user-attachments/files/16472246/latest.log)

**Comment by emilyploszaj** [comment]
These errors do not cause the looping, you have not allocated enough memory to your game.
