### ISSUE TITLE
Mod fails to load items/recipes on Quilt Loader/QSL

### ISSUE THREAD

**Issue by peanutbutter144** [emilyploszaj/emi#66]
Using EMI 0.3.3+1.19, Quilt Loader 0.17.3 and QSL/QFAPI 4.0.0-beta.9+0.60.0-1.19.2 on Minecraft 1.19.2

[latest.log](https://github.com/emilyploszaj/emi/files/9358593/latest.log)

**Comment by peanutbutter144** [comment]
The relevant part of the log:
```
[10:58:00] [Thread-13/ERROR]: Uncaught exception in thread "Thread-13"
java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/content/registry/AxeItemAccessor
	at dev.emi.emi.VanillaPlugin.register(VanillaPlugin.java:399) ~[emi-0.3.3+1.19.jar:?]
	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:99) ~[emi-0.3.3+1.19.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.content.registry.AxeItemAccessor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 3 more
```

**Comment by LemmaEOF** [comment]
...That's weird. From what I can see, [Emi's using its own `AxeItemAccessor` there](https://github.com/emilyploszaj/emi/blob/main/src/main/java/dev/emi/emi/VanillaPlugin.java#L41). Why would something try to load the Fabric one?

**Comment by LemmaEOF** [comment]
...it'd be because [that was a recent change](https://github.com/emilyploszaj/emi/commit/8e6c0908edb59114bfbfbcaed94ac134b9f29cb0)! This should be fixed when the next EMI version comes out.

**Comment by peanutbutter144** [comment]
That's good to know. I'll wait until the next release :)
