### ISSUE TITLE
[1.21 Fabric] Client log got spammed

### ISSUE THREAD

**Issue by Hiusi** [emilyploszaj/emi#663]
When joining a server, emi will send enormous number of log that makes the log file size up to 13 mbs

```
[00:41:06] [Thread-97/INFO]: [STDERR]: java.lang.AbstractMethodError: Method dev/emi/emi/jemi/impl/JemiRecipeSlotBuilder.addTypedIngredients(Ljava/util/List;)Lmezz/jei/api/gui/builder/IIngredientAcceptor; is abstract
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.impl.JemiRecipeSlotBuilder.addTypedIngredients(JemiRecipeSlotBuilder.java)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:92)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:35)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.JemiRecipe.<init>(JemiRecipe.java:55)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:263)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[00:41:06] [Thread-97/INFO]: [STDERR]: java.lang.AbstractMethodError: Method dev/emi/emi/jemi/impl/JemiRecipeSlotBuilder.addTypedIngredients(Ljava/util/List;)Lmezz/jei/api/gui/builder/IIngredientAcceptor; is abstract
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.impl.JemiRecipeSlotBuilder.addTypedIngredients(JemiRecipeSlotBuilder.java)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:92)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at mezz.jei.library.plugins.jei.tags.TagInfoRecipeCategory.setRecipe(TagInfoRecipeCategory.java:35)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.JemiRecipe.<init>(JemiRecipe.java:55)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:263)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
[00:41:06] [Thread-97/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[00:41:06] [Thread-97/INFO]: [STDERR]: java.lang.AbstractMethodError: Method dev/emi/emi/jemi/impl/JemiRecipeSlotBuilder.addTypedIngredients(Ljava/util/List;)Lmezz/jei/api/gui/builder/IIngredientAcceptor; is abstract
```

**Comment by PoptartKing99** [comment]
I'm also getting huge log spam, But I can't replicate it with just JEI and EMI installed.

**Comment by emilyploszaj** [comment]
This was fixed in a previous version and I didn't close the issue
