### ISSUE TITLE
Game crashes when resized too small

### ISSUE THREAD

**Issue by peanutbutter144** [emilyploszaj/emi#69]
Using EMI 0.3.3+1.19 on Minecraft 1.19.2 with Quilt Loader 0.17.3 and QFAPI 4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2

<details>
<summary>Crash log:</summary>

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022-08-18 17:37:26
Description: Unexpected error

java.lang.NegativeArraySizeException: -2
	at dev.emi.emi.screen.EmiScreenManager$ScreenSpace.<init>(EmiScreenManager.java:857)
	at dev.emi.emi.screen.EmiScreenManager.recalculate(EmiScreenManager.java:173)
	at dev.emi.emi.screen.EmiScreenManager.addWidgets(EmiScreenManager.java:476)
	at net.minecraft.class_465.handler$zie003$init(class_465.java:1233)
	at net.minecraft.class_465.method_25426(class_465.java:93)
	at net.minecraft.class_481.method_25426(class_481.java:327)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_481.method_25410(class_481.java:353)
	at net.minecraft.class_310.method_15993(class_310.java:1315)
	at net.minecraft.class_1041.method_4504(class_1041.java:275)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.emi.emi.screen.EmiScreenManager$ScreenSpace.<init>(EmiScreenManager.java:857)
	at dev.emi.emi.screen.EmiScreenManager.recalculate(EmiScreenManager.java:173)
	at dev.emi.emi.screen.EmiScreenManager.addWidgets(EmiScreenManager.java:476)
	at net.minecraft.class_465.handler$zie003$init(class_465.java:1233)
	at net.minecraft.class_465.method_25426(class_465.java:93)
	at net.minecraft.class_481.method_25426(class_481.java:327)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_481.method_25410(class_481.java:353)
	at net.minecraft.class_310.method_15993(class_310.java:1315)
	at net.minecraft.class_1041.method_4504(class_1041.java:275)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected level --
Details:
	All players: 1 total; [class_746['Abbie3'/77, l='ClientLevel', x=1186.48, y=-34.00, z=-1360.10]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,95,0), Section: (at 0,15,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 9330 game time, 9330 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 930813728 bytes (887 MiB) / 3219128320 bytes (3070 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.12019.5007
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21613.54
	Virtual memory used (MB): 18990.68
	Swap memory total (MB): 5303.80
	Swap memory used (MB): 89.68
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		emi: EMI 0.3.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		quilt_advancement: Quilt Advancement API 3.0.0-beta.14+1.19.2
		quilt_base: Quilt Base API 3.0.0-beta.14+1.19.2
		quilt_biome: Quilt Biome API 3.0.0-beta.14+1.19.2
		quilt_block_content_registry: Quilt Block Content Registry API 3.0.0-beta.14+1.19.2
		quilt_block_entity: Quilt Block Entity API 3.0.0-beta.14+1.19.2
		quilt_block_extensions: Quilt Block Extensions API 3.0.0-beta.14+1.19.2
		quilt_client_command: Quilt Client Command API 3.0.0-beta.14+1.19.2
		quilt_command: Quilt Command API 3.0.0-beta.14+1.19.2
		quilt_crash_info: Quilt Crash Info 3.0.0-beta.14+1.19.2
		quilt_datafixerupper: Quilt DataFixerUpper API 3.0.0-beta.14+1.19.2
		quilt_dimension: Quilt Dimension API 3.0.0-beta.14+1.19.2
		quilt_entity_multipart: Quilt Multipart Entity API 3.0.0-beta.14+1.19.2
		quilt_item_content_registry: Quilt Item Content Registry API 3.0.0-beta.14+1.19.2
		quilt_item_group: Quilt Item Group API 3.0.0-beta.14+1.19.2
		quilt_item_setting: Quilt Item Setting API 3.0.0-beta.14+1.19.2
		quilt_lifecycle_events: Quilt Lifecycle Events 3.0.0-beta.14+1.19.2
		quilt_loader: Quilt Loader 0.17.3
		quilt_networking: Quilt Networking 3.0.0-beta.14+1.19.2
		quilt_recipe: Quilt Recipe API 3.0.0-beta.14+1.19.2
		quilt_registry: Quilt Registry API 3.0.0-beta.14+1.19.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 3.0.0-beta.14+1.19.2
		quilt_resource_loader: Quilt Resource Loader 3.0.0-beta.14+1.19.2
		quilt_screen: Quilt Screen API 3.0.0-beta.14+1.19.2
		quilt_surface_rule: Quilt Surface Rule API 3.0.0-beta.14+1.19.2
		quilt_tags: Quilt Tags API 3.0.0-beta.14+1.19.2
		quilt_tooltip: Quilt Tooltip API 3.0.0-beta.14+1.19.2
		quilted_fabric_api: Quilted Fabric API 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_api_base: Quilted Fabric API Base 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_client_tags_api_v1: Quilted Fabric Client Tags 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 4.0.0-beta.9+0.60.0-1.19.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 4.0.0-beta.9+0.60.0-1.19.2
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Radeon RX 580 Series GL version 3.2.0 Core Profile Context 22.8.1.220810, ATI Technologies Inc.
	Window size: 120x1
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Abbie3'/77, l='ServerLevel[New World]', x=1186.48, y=-34.00, z=-1360.10]]
	Data Packs: vanilla
	World Generation: Stable
```

</details>

**Comment by emilyploszaj** [comment]
Fixed in 0.3.4
