### ISSUE TITLE
EMI cause fatal render excetpion (Not sure what the discriminating factor is)

### ISSUE THREAD

**Issue by SiriosDev** [emilyploszaj/emi#702]
EMI cause fatal render excetpion on search and some pages (Not sure what the discriminating factor is)
Here the log:
https://mclo.gs/5asz0LB

MC: 1.20.1
Forge: 47.3.7

I wish I could be more helpful, but I really suck at figuring out minecraft logs, the only sure thing is that activating/deactivating e makes the problem appear/disappear. In case it is not caused by emi I apologize for the report

**Comment by emilyploszaj** [comment]
This is caused by "Trimmable Tools Forge" in the log

**Comment by SiriosDev** [comment]
yes but as I said before it only happens with emi, so I thought it was a render problem

```log
at dev.emi.emi.api.stack.ItemEmiStack.isUnbatchable(ItemEmiStack.java:124) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.screen.StackBatcher.render(StackBatcher.java:171) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.screen.StackBatcher.render(StackBatcher.java:167) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.screen.EmiScreenManager$ScreenSpace.render(EmiScreenManager.java:1673) ~[emi-z.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.screen.EmiScreenManager$SidebarPanel.render(EmiScreenManager.java:1448) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.screen.EmiScreenManager.render(EmiScreenManager.java:624) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
at dev.emi.emi.platform.forge.EmiClientForge.renderScreenForeground(EmiClientForge.java:78) ~[emi-1.1.13+1.20.1+forge.jar%23592!/:?]
```

anyway if it's not from emi thank you a lot

**Comment by SiriosDev** [comment]
Yep, new relased update of trimable solved thank you a lot
