### ISSUE TITLE
1.20.1 how to bypass immersive engineering critical exception

### ISSUE THREAD

**Issue by furtabs** [emilyploszaj/emi#725]
```[11:46:43] [Thread-78/ERROR]: IRecipe#getRemainingItems was called with an inventory that does not match the recipe
[11:46:43] [Thread-78/ERROR]: according to IRecipe#matches. This is probably a bug in some mod in the following stacktrace,
[11:46:43] [Thread-78/ERROR]: if in doubt report it to Immersive Engineering
java.lang.IllegalArgumentException: null
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.getRemainingItems(AbstractFluidAwareRecipe.java:100) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23786!/:?]
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.m_7457_(AbstractFluidAwareRecipe.java:27) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23786!/:?]
	at dev.emi.emi.recipe.EmiShapedRecipe.setRemainders(EmiShapedRecipe.java:43) ~[emi-1.1.14+1.20.1+forge.jar%23726!/:?]
	at dev.emi.emi.VanillaPlugin.register(VanillaPlugin.java:425) ~[emi-1.1.14+1.20.1+forge.jar%23726!/:?]
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185) ~[emi-1.1.14+1.20.1+forge.jar%23726!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[11:46:46] [Thread-78/ERROR]: [EMI] Exception thrown registering repair recipes```

**Comment by furtabs** [comment]
This makes EMI completly hidden

**Comment by emilyploszaj** [comment]
This isssue is non-lethal and will not prevent EMI from loading, you have some other issue.
