### ISSUE TITLE
infinite "waiting for recipe data" text

### ISSUE THREAD

**Issue by VaporeonScripts** [emilyploszaj/emi#748]
![image](https://github.com/user-attachments/assets/7b509aca-a667-46bb-b7e1-0efacf6a87b0)

**Comment by VaporeonScripts** [comment]
https://mclo.gs/jO78Wtv

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .68

**Comment by fzzyhmstrs** [comment]
There are some **Forbidden and Arcanus** recipes that appear to be causing the recipe sync to fail:

```
Caused by: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:update_recipes'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:38) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.receivedPacket(GenericPacketSplitter.java:153) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.handle(GenericPacketSplitter.java:69) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	... 29 more
Caused by: io.netty.handler.codec.DecoderException: Failed to decode json: Failed to parse either. First: Failed to parse either. First: Not a json array: {"items":"productivebees:spawn_egg_configurable_bee","components":{"minecraft:entity_data":{"type":"productivebees:gold","id":"productivebees:configurable_bee"}},"type":"productivebees:component"}; Second: Not a json array: "productivebees:spawn_egg_configurable_bee"; Second: No key first in MapLike[{"items":"productivebees:spawn_egg_configurable_bee","components":{"minecraft:entity_data":{"type":"productivebees:gold","id":"productivebees:configurable_bee"}},"type":"productivebees:component"}]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.lambda$readJsonWithCodec$2(FriendlyByteBuf.java:105) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,re:classloading,pl:mixin:APP:packetfixer-common.mixins.json:FriendlyByteBufMixin from mod packetfixer,pl:mixin:A}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23108!/:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.readJsonWithCodec(FriendlyByteBuf.java:105) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:mixin,re:classloading,pl:mixin:APP:packetfixer-common.mixins.json:FriendlyByteBufMixin from mod packetfixer,pl:mixin:A}
	at TRANSFORMER/forbidden_arcanus@2.5.6-beta/com.stal111.forbidden_arcanus.common.item.crafting.ClibanoRecipe$Serializer.fromNetwork(ClibanoRecipe.java:210) ~[forbidden_arcanus-1.21.1-2.5.6-beta.jar%23763!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$1.decode(StreamCodec.java:20) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$6.decode(StreamCodec.java:108) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$8.decode(StreamCodec.java:150) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$21.decode(ByteBufCodecs.java:364) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$21.decode(ByteBufCodecs.java:358) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$7.decode(StreamCodec.java:130) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.receivedPacket(GenericPacketSplitter.java:153) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.handle(GenericPacketSplitter.java:69) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.68-universal.jar%23603!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23602!/:?] 
```

**Comment by VaporeonScripts** [comment]
What can I do about it?

**Comment by fzzyhmstrs** [comment]
I'd probably bring it up with Forbidden and Arcanus and see if they have an easy resolution. It's their mod having the problem. Or remove F&A.

**Comment by VaporeonScripts** [comment]
downgrading to version before latest of arcanus fixed the issue,i will report this

**Comment by VaporeonScripts** [comment]
this also fixes jei being broke
