### ISSUE TITLE
[Mod Compat] Sophisticated storage crafting bug

### ISSUE THREAD

**Issue by salem-5** [emilyploszaj/emi#778]
### If this issue is related to compatibility with other mods, such as missing recipes, make sure to follow these steps before reporting

When using EMI + sophisticated backpacks, the backpack crafting upgrade glitches out when i try to fill the recipe into it, and gives an error 

![ezgif-3-2380b2baef](https://github.com/user-attachments/assets/ca2f47e1-fb58-43ff-81ff-a3f7f1d930f3)

```
java.lang.NoSuchMethodError: 'net.minecraft.world.inventory.Slot mezz.jei.common.transfer.TransferOperation.craftingSlot()'
	at TRANSFORMER/sophisticatedcore@1.19.2-0.6.4.605/net.p3pp3rf1y.sophisticatedcore.compat.jei.CraftingContainerRecipeTransferHandlerBase.lambda$toMap$4(CraftingContainerRecipeTransferHandlerBase.java:131)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.6.4.605/net.p3pp3rf1y.sophisticatedcore.compat.jei.CraftingContainerRecipeTransferHandlerBase.toMap(CraftingContainerRecipeTransferHandlerBase.java:131)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.6.4.605/net.p3pp3rf1y.sophisticatedcore.compat.jei.CraftingContainerRecipeTransferHandlerBase.transferRecipe(CraftingContainerRecipeTransferHandlerBase.java:119)
	at TRANSFORMER/sophisticatedcore@1.19.2-0.6.4.605/net.p3pp3rf1y.sophisticatedcore.compat.jei.CraftingContainerRecipeTransferHandlerBase.transferRecipe(CraftingContainerRecipeTransferHandlerBase.java:39)
	at TRANSFORMER/emi@1.1.12+1.19.2+forge/dev.emi.emi.jemi.JemiRecipeHandler.jeiCraft(JemiRecipeHandler.java:133)
	at TRANSFORMER/emi@1.1.12+1.19.2+forge/dev.emi.emi.jemi.JemiRecipeHandler.craft(JemiRecipeHandler.java:77)
	at TRANSFORMER/emi@1.1.12+1.19.2+forge/dev.emi.emi.registry.EmiRecipeFiller.performFill(EmiRecipeFiller.java:123)
	at TRANSFORMER/emi@1.1.12+1.19.2+forge/dev.emi.emi.api.widget.RecipeFillButtonWidget.mouseClicked(RecipeFillButtonWidget.java:72)
	at TRANSFORMER/emi@1.1.12+1.19.2+forge/dev.emi.emi.screen.RecipeScreen.m_6375_(RecipeScreen.java:425)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at TRANSFORMER/fpsreducer@1.19.2-2.1/bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at TRANSFORMER/minecraft@1.19.2/com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197)
	at TRANSFORMER/minecraft@1.19.2/com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
- [x] Make sure the recipe exists in game and can be crafted
- [x] If the mod requires JEI, make sure both EMI and JEI are installed together
- [x] Report this issue to the mod if applicable

**Comment by IranMine123** [comment]
same as https://github.com/emilyploszaj/emi/issues/791
but instead it crashes the world:
`
Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:custom_payload' (sophisticatedcore:emi_fill_recipe)
`

**Comment by P3pp3rF1y** [comment]
the issue here is really the fact that version of sophisticatedcore that is not compatible with that version of JEI is used. So just updating to latest sophisticatedcore solves the issue.
