### ISSUE TITLE
An error is reported when digging a block

### ISSUE THREAD

**Issue by jjww748** [emilyploszaj/emi#89]
[18:28:44] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot read field "tx" because "dev.emi.emi.screen.EmiScreenManager.searchSpace" is null
	at dev.emi.emi.screen.EmiScreenManager.addWidgets(EmiScreenManager.java:485) ~[emi-0.4.0+1.19.jar:?]
	at net.minecraft.class_465.handler$cdh002$init(class_465.java:1233) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25426(class_465.java:93) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25426(class_490.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:380) ~[client-intermediary.jar:?]
	at com.plusls.MasaGadget.tweakeroo.handRestockCrafting.RestockUtil.tryCraftingRestocking(RestockUtil.java:47) ~[masa_gadget_mod-1_19_2-3.0.0-beta+1bf6939-af145baf7de2397e.jar:?]
	at fi.dy.masa.tweakeroo.util.InventoryUtils.handler$dgo000$PreRestockOnFailed(InventoryUtils.java:1237) ~[tweakeroo-fabric-1.19.2-0.14.3.jar:?]
	at fi.dy.masa.tweakeroo.util.InventoryUtils.preRestockHand(InventoryUtils.java:346) ~[tweakeroo-fabric-1.19.2-0.14.3.jar:?]
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.onProcessRightClickPre(PlacementTweaks.java:140) ~[tweakeroo-fabric-1.19.2-0.14.3.jar:?]
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.onLeftClickMousePre(PlacementTweaks.java:165) ~[tweakeroo-fabric-1.19.2-0.14.3.jar:?]
	at net.minecraft.class_310.handler$eip000$onLeftClickMousePre(class_310.java:3015) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1536(class_310.java:1685) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1999) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1829) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1135) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

**Comment by emilyploszaj** [comment]
I forgot to close this a long time ago, the underlying code base has changed significantly at this point and I've not had a report about this so I will be assuming it is resolved.
